서버 시작 대기 부분 끈 상태로 테스트

diff --git a/.github/workflows/test-server.yml b/.github/workflows/test-server.yml
--- a/.github/workflows/test-server.yml
+++ b/.github/workflows/test-server.yml
@@ -49,35 +49,29 @@ jobs:
           Start-Process "uvicorn" -ArgumentList "app.main:app --host 0.0.0.0 --port 5835" -NoNewWindow
           Write-Host "FastAPI server started on port 5835"
 
-      # 6. 서버 시작 대기
-      - name: Wait for server to start
-        run: |
-          $retries = 10
-          $success = $false
-          for ($i=0; $i -lt $retries; $i++) {
-            try {
-              $response = Invoke-WebRequest -Uri "http://127.0.0.1:5835" -Method GET
-              if ($response.StatusCode -eq 200) {
-                $success = $true
-                break
-              }
-            }
-            catch {
-              Start-Sleep -Seconds 3
-            }
-          }
-          if (-not $success) {
-            Write-Host "Server did not start in time"
-            exit 1
-          }
+      # # 6. 서버 시작 대기
+      # - name: Wait for server to start
+      #   run: |
+      #     $retries = 10
+      #     $success = $false
+      #     for ($i=0; $i -lt $retries; $i++) {
+      #       try {
+      #         $response = Invoke-WebRequest -Uri "http://127.0.0.1:5835" -Method GET
+      #         if ($response.StatusCode -eq 200) {
+      #           $success = $true
+      #           break
+      #         }
+      #       }
+      #       catch {
+      #         Start-Sleep -Seconds 3
+      #       }
+      #     }
+      #     if (-not $success) {
+      #       Write-Host "Server did not start in time"
+      #       exit 1
+      #     }
 
-      # 7. /mongo/restday-update-db 호출 (curl 사용)
-      - name: Call MongoDB Update API using curl
-        run: |
-          curl.exe -v -X GET "http://127.0.0.1:5835/mongo/restday-update-db"
-          Write-Host "finished work"
-
-      # 8. /mongo/restday-update-db 호출 (Invoke-WebRequest 사용)
+      # 7. /mongo/restday-update-db 호출 (Invoke-WebRequest 사용)
       - name: Call MongoDB Update API using Invoke-WebRequest
         run: |
           Invoke-WebRequest -Uri "http://127.0.0.1:5835/mongo/restday-update-db" -Method GET
